### ISSUE TITLE
WSL2 sometimes hangs when accessing Windows executables, which is a Big Problem for us

### ISSUE THREAD

**Issue by anaisbetts** [arquivolta/docs#7]
Because of how we redirect OpenSSH => ssh.exe, this bug in WSL2 hurts like 100x more than it normally would.

https://github.com/microsoft/WSL/issues/7371

**Comment by OneBlue** [comment]
Probably a duplicate of #7883, closing

**Comment by anaisbetts** [comment]
Fixed!
